services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - ./.env.production.local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - ./.env.production.local

    ports:
      - "8888:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /mailhog/data
    volumes:
      - mailhog_data:/mailhog/data
  backend:
    build:
      context: .
    container_name: app-backend
    env_file:
      - ./.env.production.local
    depends_on:
      - postgres
    ports:
      - "5050:3000"
    restart: always
    volumes:
      - ./public:/app/public
    networks:
      - app-network

volumes:
  postgres_data:
    name: flipkart_postgres_data
  pgadmin_data:
    name: flipkart_pgadmin_data
  mailhog_data:
    name: flipkart_mailhog_data

networks:
  app-network:
    external: true
